# -------------------------------------------------------------------
# InfraVault-Labs - Inventario de Producción (Kit de Infraestructura)
# -------------------------------------------------------------------

[proxmox]
pvm-01 ansible_host=192.168.100.11 ansible_user=root
pvm-02 ansible_host=192.168.100.12 ansible_user=root

[storage]
truenas ansible_host=192.168.100.13 ansible_user=root

[firewall]
pfsense ansible_host=192.168.100.1 ansible_user=admin

# Grupo global que unifica toda la infraestructura local
[production:children]
proxmox
storage
firewall

[production:vars]
# Optimización de conexión para entornos de red con latencia en Caracas
ansible_connection=ssh
ansible_ssh_timeout=30
ansible_python_interpreter=/usr/bin/python3